// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2877.KareemAbdulJabBot2012;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Jaguar driveTrainJaguarL1;
    public static Jaguar driveTrainJaguarL2;
    public static Jaguar driveTrainJaguarR1;
    public static Jaguar driveTrainJaguarR2;
    public static RobotDrive driveTrainRobotDrive41;
    public static Jaguar shooterJaguarS1;
    public static Jaguar shooterJaguarS2;
    public static Jaguar pickupJaguarP1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
            driveTrainJaguarL1 = new Jaguar(1);
	
            driveTrainJaguarL2 = new Jaguar(2);

            driveTrainJaguarR1 = new Jaguar(3);

            driveTrainJaguarR2 = new Jaguar(4);

            driveTrainRobotDrive41 = new RobotDrive(driveTrainJaguarL1, driveTrainJaguarL2,
              driveTrainJaguarR1, driveTrainJaguarR2);
	
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);
        
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);

        shooterJaguarS1 = new Jaguar(5);
        
        shooterJaguarS2 = new Jaguar(6);

        pickupJaguarP1 = new Jaguar(7);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
